# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aparcamientos', '0002_aparcamiento_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.FloatField(choices=[(5.0, 'HUGE'), (3.0, 'LARGE'), (1.0, 'NORMAL'), (0.75, 'SMALL'), (0.5, 'TINY')], default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='comentario',
            name='selected_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
