# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0003_auto_20170517_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aparcamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='selected_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
