# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aparcamientos', '0005_auto_20170517_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='accesibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='clase_vial',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='distrito',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='nombre_via',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='selected_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estilo',
            name='page_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
