# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0006_auto_20170518_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='barrio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='clase_vial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='distrito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='nombre_via',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='page_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
