# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0007_auto_20170518_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparcamiento',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
