# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0008_auto_20170518_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='horario',
            field=models.TextField(null=True),
        ),
    ]
