# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0009_aparcamiento_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparcamiento',
            name='horario',
        ),
    ]
