# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0010_remove_aparcamiento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparcamiento',
            name='selected_by',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
