# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0011_auto_20170518_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='identificador',
            field=models.IntegerField(null=True),
        ),
    ]
