# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0012_aparcamiento_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='numero_comentarios',
            field=models.IntegerField(default=0),
        ),
    ]
