# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0014_estilo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
