# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0016_aparcamiento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparcamiento',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
