# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0017_auto_20170522_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='telefono',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
