# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0018_auto_20170522_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamiento',
            name='latitud',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='longitud',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
