# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aparcamientos', '0019_auto_20170523_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuando', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='selection',
            name='aparcamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento'),
        ),
        migrations.AddField(
            model_name='selection',
            name='selected_by',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
