# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0021_auto_20170523_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='background_color',
            field=models.CharField(default='white', max_length=15),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='font_size',
            field=models.FloatField(default=1.0),
        ),
    ]
